V4
Meteor-Community-Packages/meteor-fast-render pull request #1
Opened 2021-04-15 03:08 UTC by copleykj

1. Adds FastRender.onDataReady callback to simplify timing control
2. Adds Extra Data API for sending non pub/sub data with the HTML payload
3. Removes dependency on underscore because modern syntax makes it unnecessary 
4. Improves code structure and refactors to modern syntax, for comprehension and sanity

2021-04-16 06:27 UTC, jankapunkt commented
I have some general suggestions / feedback regarding documentation / code quality

- What do you think about adding a contribution (how to run the linter and tests etc.) section to the README?
- link the `qa/README.md` into the README (or is this file outdated?)
- Running `standard` shows me lint errors (many but only the same kind, `Expected indentation of 2 spaces but found 1 tab`)
- Is the CI still working`I see a `.travis` file in there but can't find it on travis-ci. Maybe move to GitHub CI? I have a working [example repo with Meteor CI on GitHub](https://github.com/leaonline/leaonline-accounts/tree/master/.github/workflows) (for packages this works also great when being [wrapped inside a bare project](https://github.com/serut/meteor-coverage/#specific-setup-for-meteor-package))

What do you think?

2021-04-22 22:57 UTC, copleykj commented
@jankapunkt Thanks for the feedback!

I think adding a contribution section, as well as setting up GitHub CI is a great idea. I've removed the travis config file as well as `qa/README.md` as they were presumable artifacts of the original meteorhacks repo and for QA I'd much rather see that fall on tests and not have to do it manually.

As far as linting using the standard command and getting errors, using eslint is probably best since I don't think standard will respect the rules supplied in the eslint config. Honestly though, as far as I'm concerned this config need reworked, getting rid of tabs and adding semicolons, and trailing commas for multiline.

I should be able to start on these changes tonight, and once that's finished, I'll set up husky with a precommit hook that runs eslint.

2021-04-30 15:31 UTC, StorytellerCZ requested changes

2021-04-30 15:31 UTC, StorytellerCZ commented on lib/server/publish_context.js
> +  console.warn(
Maybe instead of console we could use the `logging` package for these.

2021-04-30 18:58 UTC, StorytellerCZ approved these changes

2021-04-30 20:22 UTC, copleykj commented
I'm still working to create a solution so that #2 doesn't crop up again. More changes on the way soon.

2021-05-06 18:23 UTC, jankapunkt commented
@copleykj yes you can create a bare test project and use `.meteorignore` to keep it out of the published package. I did that with Autoform and since you can then use meteortesting:mocha, chai, sinon and puppeteer you can basically test anything.

2021-05-11 02:16 UTC, copleykj commented
ok, so tests are migrated to `meteortesting:mocha` and everything is passing. @jankapunkt will `.meteorignore` actually keep the test app out of the published package? I seem to remember trying to use it to keep `node_modules` out and it failing to do so.

2021-05-11 05:51 UTC, jankapunkt commented
@copleykj is there a way to verify that? I based this assumption on the [documentation](https://guide.meteor.com/build-tool.html#compiles-with-build-plugins) and can at least confirm, that it skipped installing the dev dependencies when deploying my app instead of the case where the was no `.meteorignore`

2021-05-11 14:17 UTC, copleykj commented
Ok, the testApp directory that I specified in `.meteorignore` **does not** make it into the tarball and so we should be good to go using that method.

2021-05-11 14:32 UTC, copleykj commented
It does seem to still include certain directories such as tests, so I think there's a possibility that might have been what was happing with the node_modues dir previously.

![Screenshot_2021-05-11_10-24-15](https://user-images.githubusercontent.com/1511556/117833277-30bac980-b244-11eb-8260-b22d87092151.png)

2021-05-13 18:28 UTC, copleykj commented
I think things are in pretty good shape at this point. I don't think I'm gonna set up CI right now as I have quite a bit of reading to do and lots to figure out before I'm confident it gets done right.

2021-05-13 18:33 UTC, jankapunkt commented
@copleykj GitHub actions take indeed some time to understand when coming from other services like Circle, Travis etc.
I have set up actions for AutoForm so you can peek into it if you need some examples. I can also provide some more complex examples using artifacts, chaining jobs, cloning repos etc., just let me know.

2021-05-14 15:24 UTC, merged